### ISSUE TITLE
Imagenet data format

### ISSUE THREAD

**Issue by yezhengli-Mr9** [csinva/hierarchical-dnn-interpretations#2]
For Imagenet (jupyter notebook), you data format should be (for example, 32 by 32 imagenet val, all in *.jpg in 'val/', correct?

**Comment by csinva** [comment]
Thanks for the interest! For the Imagenet jupyter notebook here, you don't need to add any .jpg files since I have already included a few images in a .pkl file. That .pkl file is all these notebooks need!

If you want to download imagenet for your own use / train a new model, you will need to download the .jpg files. There are some instructions on how to do this [here](https://github.com/csinva/imagenet_quickstart_pytorch).

**Comment by yezhengli-Mr9** [comment]
> 
> 
> Thanks for the interest! For the Imagenet jupyter notebook here, you don't need to add any .jpg files since I have already included a few images in a .pkl file. That .pkl file is all these notebooks need!
> 
> If you want to download imagenet for your own use / train a new model, you will need to download the .jpg files. There are some instructions on how to do this [here](https://github.com/csinva/imagenet_quickstart_pytorch).

Thanks, I am commenting out second cell (of the notebook) and retry (on cpu only mode). Up till now, no need to retrain model -- just run through notebook; if it works, then I am to apply to other network (not vgg16).

**Comment by yezhengli-Mr9** [comment]
Hi Chandan, any short explanation for using ```im_torch``` and ```im_origin``` separately?

**Comment by csinva** [comment]
Hello, 

I think you may want to work through some tutorials on pytorch before starting to use this repo.

im_torch is of type torch.Tensor (used to be passed through networks)

im_orig is of type np array (used to visualize and other things).

**Comment by yezhengli-Mr9** [comment]
Thanks for your patience, Chandan. I am not asking that basic questions but the problem is solved anyway. 
I should check many times before bothering you.
Thanks again for your patience, you are a super nice author/ programmer!
Yezheng
