### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by cvrmurthy** [csinva/hierarchical-dnn-interpretations#4]
Please correct hard coded path ........../imagenet from the load_data method on .../dsets/imagenet/dset.py

**Comment by cvrmurthy** [comment]
Another issue that I faced is with version of packages
torch==1.2.0 
torchvision==0.4.0 
foolbox (Missing in dependencies)

Code does not get executed with the latest and greatest versions of the above.

Environment:
Ubuntu 18.04.4 LTS (Local)
Tried on Google Colab as well with the same result.

**Comment by csinva** [comment]
Thanks for using the code and pointing these things out! 

Regarding the hard-coded path, I'll change it a little so that the hardcoded path isn't default (but note that this function does still take in the filepath to wherever you have imagenet stored).

I will look into issues with these latest version...(if you have more details on the error let me know!)

P.S. Foolbox is missing since it's only used if one wants to reproduce the adversarial experiments, and isn't core to the module.
